version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - API_SECRET=${API_SECRET}
    volumes:
      - ./api_data:/app/data
    depends_on:
      - db
      - cache
    networks:
      - excel_network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api
    networks:
      - excel_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - excel_network

  cache:
    image: redis:6
    volumes:
      - redis_data:/data
    networks:
      - excel_network

  collaboration:
    build:
      context: ../src/collaboration-services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://cache
    depends_on:
      - cache
    networks:
      - excel_network

volumes:
  postgres_data:
  redis_data:
  api_data:

networks:
  excel_network:
    driver: bridge