---
- name: Update and upgrade system packages
  apt:
    upgrade: yes
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Configure firewall rules
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '22'
    - '80'
    - '443'

- name: Install and configure intrusion detection system
  package:
    name: fail2ban
    state: present

- name: Set up and configure antivirus software
  package:
    name: clamav
    state: present

- name: Implement secure SSH configuration
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0600'

- name: Configure and enable SELinux
  selinux:
    policy: targeted
    state: enforcing
  when: ansible_os_family == 'RedHat'

- name: Set up automated security updates
  apt:
    name: unattended-upgrades
    state: present
  when: ansible_os_family == 'Debian'

- name: Implement strong password policies
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^minlen'
    line: 'minlen = 14'

- name: Configure audit logging
  package:
    name: auditd
    state: present

- name: Set up file integrity monitoring
  package:
    name: aide
    state: present

- name: Implement network segmentation
  iptables:
    chain: INPUT
    source: "{{ internal_network }}"
    jump: ACCEPT

- name: Configure TLS/SSL for all services
  openssl_certificate:
    path: /etc/ssl/certs/excel_cert.pem
    privatekey_path: /etc/ssl/private/excel_key.pem
    provider: selfsigned

- name: Set up and configure a centralized logging system
  template:
    src: templates/rsyslog.conf.j2
    dest: /etc/rsyslog.conf

- name: Implement multi-factor authentication
  package:
    name: libpam-google-authenticator
    state: present
  when: ansible_os_family == 'Debian'

- name: Configure data encryption at rest
  luks_device:
    device: /dev/sdb
    name: encrypted_data
    state: present

- name: Set up regular security scans
  cron:
    name: Weekly security scan
    weekday: '0'
    hour: '2'
    minute: '0'
    job: /usr/bin/clamscan -r /

- name: Implement backup and disaster recovery procedures
  cron:
    name: Daily backup
    hour: '1'
    minute: '0'
    job: /usr/local/bin/backup_script.sh

- name: Configure compliance-related settings
  template:
    src: templates/compliance_settings.j2
    dest: /etc/excel/compliance_settings.conf

- name: Set up monitoring and alerting for security events
  template:
    src: templates/security_monitoring.j2
    dest: /etc/excel/security_monitoring.conf

- name: Implement least privilege access controls
  user:
    name: excel_app
    groups: excel_users
    append: yes