apiVersion: v1
kind: Secret
metadata:
  name: excel-secrets
  namespace: excel-namespace
  labels:
    app: excel
type: Opaque
data:
  DB_PASSWORD: <base64EncodedPassword>
  API_KEY: <base64EncodedApiKey>
  JWT_SECRET: <base64EncodedJwtSecret>
  ENCRYPTION_KEY: <base64EncodedEncryptionKey>

# Human tasks:
# 1. Replace <base64EncodedPassword> with the actual base64-encoded database password
# 2. Replace <base64EncodedApiKey> with the actual base64-encoded API key
# 3. Replace <base64EncodedJwtSecret> with the actual base64-encoded JWT secret
# 4. Replace <base64EncodedEncryptionKey> with the actual base64-encoded encryption key
# 5. Ensure that this file is not committed to version control
# 6. Implement a secure method to generate and manage these secrets
# 7. Set up a process for regular rotation of these secrets
# 8. Consider integrating with external secret management systems (e.g., Azure Key Vault, AWS Secrets Manager)